"""fix future annotations

Revision ID: 2c84f4cefa08
Revises: 0736a4bcc669
Create Date: 2026-05-15 12:29:22.509757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c84f4cefa08'
down_revision: Union[str, Sequence[str], None] = ('0736a4bcc669', 'b1c2d3e4f5g6')
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_progress', sa.Column('max_streak', sa.Integer(), nullable=False))
    op.add_column('user_progress', sa.Column('study_days', sa.Integer(), nullable=False))
    op.add_column('user_progress', sa.Column('chats_count', sa.Integer(), nullable=False))
    op.add_column('user_progress', sa.Column('cards_done', sa.Integer(), nullable=False))
    op.add_column('user_progress', sa.Column('roadmaps_count', sa.Integer(), nullable=False))
    op.add_column('user_progress', sa.Column('total_minutes', sa.Integer(), nullable=False))
    op.add_column('user_progress', sa.Column('activity_map', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_progress', 'activity_map')
    op.drop_column('user_progress', 'total_minutes')
    op.drop_column('user_progress', 'roadmaps_count')
    op.drop_column('user_progress', 'cards_done')
    op.drop_column('user_progress', 'chats_count')
    op.drop_column('user_progress', 'study_days')
    op.drop_column('user_progress', 'max_streak')
    # ### end Alembic commands ###
