"""add cards and roadmap to chat_sessions

Revision ID: 655dc090ddd6
Revises: a1b2c3d4e5f6
Create Date: 2026-05-09 16:32:59.550153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '655dc090ddd6'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('cards', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('chat_sessions', sa.Column('roadmap', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('chat_sessions', sa.Column('card_index', sa.Integer(), nullable=True))
    op.add_column('chat_sessions', sa.Column('card_wrong', sa.Integer(), nullable=True))
    op.add_column('chat_sessions', sa.Column('card_right', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'card_right')
    op.drop_column('chat_sessions', 'card_wrong')
    op.drop_column('chat_sessions', 'card_index')
    op.drop_column('chat_sessions', 'roadmap')
    op.drop_column('chat_sessions', 'cards')
    # ### end Alembic commands ###
